### ISSUE TITLE
Democracy Module - Display names instead of ID's

### ISSUE THREAD

**Issue by lydonb** [lydonb/robort#19]
When we're voting on something using the democracy module, the counted votes should be displayed as user names instead of ID's.

**Example:**
robortBOT [9:27 AM] 
3: what is the official spelling of robert gouge's nickname?

robortBOT [9:27 AM]
1: doug - 3 (U02F06WHT, U030BHX4Z, U02HY4DT9)

robortBOT [9:27 AM]
2: Dug - 3 (U02N91B8Q, U02K6H5Q2, U02KAT9LY)

robortBOT [9:27 AM]
3: gouge - 0 ()

**Comment by Retzy** [comment]
This was fixed.
