### ISSUE TITLE
Karma Module - Limit karma points per day

### ISSUE THREAD

**Issue by lydonb** [lydonb/robort#20]
Add the ability to limit the amount of karma given out by an individual in a single day. Probably using a configurable environment variable. Data is stored in robot.brain.

**Comment by everyonce** [comment]
Per some suggestions of 'resetting' karma, I'm going to suggest karma 'decay' as well...

**Comment by newtonrd** [comment]
I am against this idea @everyonce. It's your karma, you can keep it.

**Comment by lydonb** [comment]
#22
