### ISSUE TITLE
unvoted question prompt on user joining new channel

### ISSUE THREAD

**Issue by everyonce** [lydonb/robort#30]

**Comment by everyonce** [comment]
peezy [3:10 PM] 
joined #rantroom

robortBOT [3:10 PM] 
U043JKZBM: unvoted question, please see !question 2

**Comment by newtonrd** [comment]
https://github.com/lydonb/robort/blob/master/scripts/democracy.coffee#L118

Seems to be a feature

**Comment by lydonb** [comment]
#22
